language: python
sudo: required
python:
  - "3.6"
services:
  - docker
install:
  - make server.install
  - make database.init
  - make database.migrate
script:
  - make server.test
  - make server.flake8
after_success:
  - make server.d
  - pip install bs4 requests
  - python scrap/scrap.py
