language: python
sudo: required
python:
  - "3.6"
services:
  - docker
before_install:
  - make server.install
  - make database.init
  - make database.migrate
  - make scrap.scrap
script:
  - make server.test
  - make server.flake8
