language: python
sudo: required
python:
  - "3.6"
services:
  - docker
install:
  - make server.install
  - make database.init
  - make database.migrate
  - python scrap/scrap.py
script:
  - make server.test
  - make server.flake8
