language: python
sudo: required
python:
  - "3.6"
services:
  - docker
before_install:
  - make server.install
  - make database.init
  - make database.migrate
  - make database.upgrade
script:
  - make server.test
